In [4]:
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

# Load your data into a pandas DataFrame
data = pd.read_csv("your_data.csv")

# Fit mixed-effects model
mixed_model = smf.mixedlm("outcome_variable ~ predictor1 + predictor2 + ...", data, groups=data["country"])
mixed_result = mixed_model.fit()

# Print summary of the model
print(mixed_result.summary())

KeyboardInterrupt:

In [5]:
import pandas as pd

### Create master ISO list

In [6]:
ISO_df = pd.read_csv(r"C:\Users\marc1\OneDrive\Desktop\School\Aarhus University\Current Classes\DSPF\DSPF_Final\Data\ISO_list.csv")
ISO_masterlist = ISO_df['alpha-3'].tolist()
print(ISO_masterlist)

['AFG', 'ALA', 'ALB', 'DZA', 'ASM', 'AND', 'AGO', 'AIA', 'ATA', 'ATG', 'ARG', 'ARM', 'ABW', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB', 'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BES', 'BIH', 'BWA', 'BVT', 'BRA', 'IOT', 'BRN', 'BGR', 'BFA', 'BDI', 'CPV', 'KHM', 'CMR', 'CAN', 'CYM', 'CAF', 'TCD', 'CHL', 'CHN', 'CXR', 'CCK', 'COL', 'COM', 'COG', 'COD', 'COK', 'CRI', 'CIV', 'HRV', 'CUB', 'CUW', 'CYP', 'CZE', 'DNK', 'DJI', 'DMA', 'DOM', 'ECU', 'EGY', 'SLV', 'GNQ', 'ERI', 'EST', 'SWZ', 'ETH', 'FLK', 'FRO', 'FJI', 'FIN', 'FRA', 'GUF', 'PYF', 'ATF', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA', 'GIB', 'GRC', 'GRL', 'GRD', 'GLP', 'GUM', 'GTM', 'GGY', 'GIN', 'GNB', 'GUY', 'HTI', 'HMD', 'VAT', 'HND', 'HKG', 'HUN', 'ISL', 'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'IMN', 'ISR', 'ITA', 'JAM', 'JPN', 'JEY', 'JOR', 'KAZ', 'KEN', 'KIR', 'PRK', 'KOR', 'KWT', 'KGZ', 'LAO', 'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LIE', 'LTU', 'LUX', 'MAC', 'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT', 'MHL', 'MTQ', 'MRT', 'MUS', 'MYT', 'MEX', 'FSM', 'MDA', 'MCO', 'MNG', 'MNE', 'MSR', 'MAR', 'MOZ', 'MMR', 'NAM', 'NRU', 'NPL', 'NLD', 'NCL', 'NZL', 'NIC', 'NER', 'NGA', 'NIU', 'NFK', 'MKD', 'MNP', 'NOR', 'OMN', 'PAK', 'PLW', 'PSE', 'PAN', 'PNG', 'PRY', 'PER', 'PHL', 'PCN', 'POL', 'PRT', 'PRI', 'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'BLM', 'SHN', 'KNA', 'LCA', 'MAF', 'SPM', 'VCT', 'WSM', 'SMR', 'STP', 'SAU', 'SEN', 'SRB', 'SYC', 'SLE', 'SGP', 'SXM', 'SVK', 'SVN', 'SLB', 'SOM', 'ZAF', 'SGS', 'SSD', 'ESP', 'LKA', 'SDN', 'SUR', 'SJM', 'SWE', 'CHE', 'SYR', 'TWN', 'TJK', 'TZA', 'THA', 'TLS', 'TGO', 'TKL', 'TON', 'TTO', 'TUN', 'TUR', 'TKM', 'TCA', 'TUV', 'UGA', 'UKR', 'ARE', 'GBR', 'USA', 'UMI', 'URY', 'UZB', 'VUT', 'VEN', 'VNM', 'VGB', 'VIR', 'WLF', 'ESH', 'YEM', 'ZMB', 'ZWE']

## Population DF

In [7]:
pop_df = pd.read_excel(r"C:\Users\marc1\OneDrive\Desktop\School\Aarhus University\Current Classes\DSPF\DSPF_Final\Population Data.xlsx")

In [8]:
display(pop_df)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720859132.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,...,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1790133.0,1786038.0,1761985.0
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5542459.0,5646668.0,5753386.0,5860197.0,5973803.0,6097298.0,...,26984002.0,27753304.0,28516545.0,29274002.0,30034389.0,30790513.0,31546691.0,32284046.0,32981641.0,33696614.0
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,16520441.0,16989464.0,17503133.0,18042215.0,18603097.0,19187194.0,...,53873616.0,54729551.0,55876504.0,56422274.0,56641209.0,57339635.0,58087055.0,58801927.0,59392255.0,59893885.0
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3119430.0,3219451.0,3323427.0,3431381.0,3542764.0,3658024.0,...,15234976.0,15737793.0,16248230.0,16767761.0,17298054.0,17835893.0,18380477.0,18927715.0,19473125.0,20017675.0
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3806310.0,3925952.0,4049778.0,4177931.0,4310332.0,4447149.0,...,13555422.0,13855753.0,14154937.0,14452704.0,14751101.0,15052184.0,15354608.0,15669666.0,15993524.0,16320537.0

In [9]:
# Melt the DataFrame to transform the years into a single column
population_df = pd.melt(pop_df, id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
                    var_name='Year', value_name='Value')

# Drop unneeded columns
population_df.drop(columns=['Indicator Name', 'Indicator Code'], inplace=True)
# Rename column 'A' to 'New_A'
population_df.rename(columns={'Value': 'Population, total'}, inplace=True)

# Print the resulting DataFrame
display(population_df)

                      Country Name Country Code  Year  Population, total
0                            Aruba          ABW  1960            54608.0
1      Africa Eastern and Southern          AFE  1960        130692579.0
2                      Afghanistan          AFG  1960          8622466.0
3       Africa Western and Central          AFW  1960         97256290.0
4                           Angola          AGO  1960          5357195.0
...                            ...          ...   ...                ...
16753                       Kosovo          XKX  2022          1761985.0
16754                  Yemen, Rep.          YEM  2022         33696614.0
16755                 South Africa          ZAF  2022         59893885.0
16756                       Zambia          ZMB  2022         20017675.0
16757                     Zimbabwe          ZWE  2022         16320537.0

[16758 rows x 4 columns]

## Country Size DF

In [ ]:
size_df = pd.read_excel(r"C:\Users\marc1\OneDrive\Desktop\School\Aarhus University\Current Classes\DSPF\DSPF_Final\Data\Country Size.xlsx")
display(size_df)

In [ ]:
# Melt the DataFrame to transform the years into a single column
consize_df = pd.melt(size_df, id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
                    var_name='Year', value_name='Value')

# Drop unneeded columns
consize_df.drop(columns=['Indicator Name', 'Indicator Code'], inplace=True)
# Rename column 'A' to 'New_A'
consize_df.rename(columns={'Value': 'Land area (sq. km)'}, inplace=True)

# Filter rows based on whether the country code is in the predefined list
consize_df = consize_df[consize_df['Country Code'].isin(ISO_masterlist)]

# Print the resulting DataFrame
display(consize_df)

## WGI Data

In [106]:
voice_account_df = pd.read_excel(r"C:\Users\marc1\OneDrive\Desktop\School\Aarhus University\Current Classes\DSPF\DSPF_Final\Data\wgidataset.xlsx", sheet_name= "VoiceandAccountability")

# Set the headers as the values in the first row (index 13)
voice_account_df.columns = voice_account_df.iloc[13]

# Drop the first ten rows
voice_account_df = voice_account_df.drop(index=range(12))

# Reset the index after dropping rows
voice_account_df = voice_account_df.reset_index(drop=True)

# Set the headers as the values in the first row (index 0)
voice_account_df.columns = voice_account_df.iloc[0]

# Filter columns based on whether row 2 contains the word "Estimate"
voice_account_df = voice_account_df.iloc[:, :2].join(voice_account_df.loc[:, voice_account_df.iloc[1] == 'Estimate'])

display(voice_account_df)

,Country/Territory,Code,1996,1998,2000,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Country/Territory,Code,1996,1998,2000,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,Country/Territory,Code,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,...,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
2,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,0.737521,1.15323,1.017273,...,1.278059,1.27685,1.273961,1.279364,1.295549,1.282693,1.262558,1.282143,1.018641,1.009182
3,Andorra,ADO,1.563217,1.528759,1.535655,1.437128,1.422262,1.563077,1.528182,1.329979,...,1.406642,1.165965,1.194495,1.176597,1.161656,1.047322,1.108412,1.086253,1.033413,1.102833
4,Afghanistan,AFG,-1.90854,-2.039301,-2.031417,-1.433421,-1.177571,-1.203034,-1.12543,-1.110294,...,-1.240068,-1.13544,-1.117557,-1.037788,-0.990814,-1.007052,-1.006575,-1.077689,-1.56789,-1.751587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,Serbia,SRB,-1.215804,-0.973843,-0.637738,0.003406,-0.120494,-0.17605,-0.206955,0.214459,...,0.285488,0.212629,0.231072,0.199925,0.117244,-0.014972,-0.046881,-0.120646,-0.127868,-0.099995
212,South Africa,ZAF,0.841139,0.846978,0.74624,0.659822,0.700217,0.715737,0.64901,0.651613,...,0.600703,0.640374,0.648585,0.648347,0.630478,0.637541,0.642935,0.688375,0.770391,0.707014
213,"Congo, Dem. Rep.",ZAR,-1.600949,-1.728647,-1.733551,-1.609575,-1.555048,-1.697053,-1.521638,-1.230791,...,-1.458554,-1.286946,-1.304218,-1.412191,-1.465801,-1.499192,-1.314188,-1.25271,-1.185847,-1.183693
214,Zambia,ZMB,-0.334019,-0.483754,-0.413114,-0.317013,-0.36678,-0.444225,-0.430346,-0.207338,...,-0.106042,-0.109431,-0.066544,-0.30062,-0.335554,-0.336164,-0.30962,-0.428919,-0.369448,-0.089141
215,Zimbabwe,ZWE,-0.61155,-0.789812,-1.085388,-1.363361,-1.431192,-1.553577,-1.674941,-1.539244,...,-1.38622,-1.256889,-1.166087,-1.17846,-1.195905,-1.136798,-1.163669,-1.113408,-1.13583,-1.102206

In [ ]:
# Melt the DataFrame to transform the years into a single column
consize_df = pd.melt(size_df, id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
                    var_name='Year', value_name='Value')

# Drop unneeded columns
consize_df.drop(columns=['Indicator Name', 'Indicator Code'], inplace=True)
# Rename column 'A' to 'New_A'
consize_df.rename(columns={'Value': 'Land area (sq. km)'}, inplace=True)

# Filter rows based on whether the country code is in the predefined list
consize_df = consize_df[consize_df['Country Code'].isin(ISO_masterlist)]

# Print the resulting DataFrame
display(consize_df)